#pragma once
#include <string>
#include <vector>
#include <map>
#include <iostream>
#include <random>
#include <fstream>
#include <sstream>

using std::string;
using std::vector;
using std::map;
using std::cout;
using std::cin;
using std::endl;
using std::mt19937;
using std::uniform_int_distribution;
using std::random_device;
using std::ifstream;
using std::istringstream;
